#Import Packages and Connect to Drive

In [ ]:
!python --version

Python 3.7.15


In [ ]:
import os
os.getcwd()

'/home/wsuser/work'

In [ ]:
import os
import IPython.display as ipd
import matplotlib.pyplot as plt#graph plotting
import numpy as np#Array or Multi dimi. arrays
import pandas as pd#Reading files and sving it as tablur format
import time
from collections import Counter, OrderedDict#[1,2,3,3]
import cv2#opencv - python - Image processing- short form -cv2
#from google.colab.patches import cv2_imshow#Is used for printing the images
import random#Generating random variables or values
#import seaborn as sns#graph plotting
import json
import joblib
import pickle
from ibm_watson_machine_learning import APIClient

In [ ]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 1.0.2.


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.utils import class_weight
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.exceptions import NotFittedError
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn import metrics

#Data Loading and Preprocessing

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='geDl8EdyQxhVAqykYTv3jPIjXaicgiET0P6yZji-ubLg',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.eu.cloud-object-storage.appdomain.cloud",

SyntaxError: ignored

In [ ]:
bucket = 'rainfall-donotdelete-pr-eoii6hshulobg1'
object_key = 'rainfall.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df

NameError: ignored

In [ ]:
df = df.dropna()
df

NameError: ignored

In [ ]:
for i in df.columns:
  print(i, df[i].dtype)
  print(df[i].value_counts())
  print("################")

Date object
2010-11-16    25
2009-03-09    25
2009-03-28    25
2009-03-26    25
2010-05-17    25
              ..
2008-03-26     1
2008-03-25     1
2008-03-24     1
2008-03-23     1
2008-01-02     1
Name: Date, Length: 3416, dtype: int64
################
Location object
Darwin              3062
Perth               3025
Brisbane            2953
MelbourneAirport    2929
PerthAirport        2913
SydneyAirport       2870
Watsonia            2730
Mildura             2594
MountGambier        2465
NorfolkIsland       2464
Cairns              2444
Townsville          2419
WaggaWagga          2416
AliceSprings        2223
Nuriootpa           2008
Hobart              1939
Moree               1913
Melbourne           1898
Portland            1863
Woomera             1734
Sydney              1690
Sale                1678
CoffsHarbour        1380
Williamtown         1198
Canberra            1078
Cobar                534
Name: Location, dtype: int64
################
MinTemp float64
 13.0    349
 9.6

In [ ]:
cols = ['RainToday', 'RainTomorrow', 'WindDir3pm', 'WindDir9am', 'WindGustDir', 'Location']

In [ ]:
le = LabelEncoder()
for col in cols:
  print(col)
  df[col] = le.fit_transform(df[col])
  le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
  print(le_name_mapping)
  print("################")

RainToday
{'No': 0, 'Yes': 1}
################
RainTomorrow
{'No': 0, 'Yes': 1}
################
WindDir3pm
{'E': 0, 'ENE': 1, 'ESE': 2, 'N': 3, 'NE': 4, 'NNE': 5, 'NNW': 6, 'NW': 7, 'S': 8, 'SE': 9, 'SSE': 10, 'SSW': 11, 'SW': 12, 'W': 13, 'WNW': 14, 'WSW': 15}
################
WindDir9am
{'E': 0, 'ENE': 1, 'ESE': 2, 'N': 3, 'NE': 4, 'NNE': 5, 'NNW': 6, 'NW': 7, 'S': 8, 'SE': 9, 'SSE': 10, 'SSW': 11, 'SW': 12, 'W': 13, 'WNW': 14, 'WSW': 15}
################
WindGustDir
{'E': 0, 'ENE': 1, 'ESE': 2, 'N': 3, 'NE': 4, 'NNE': 5, 'NNW': 6, 'NW': 7, 'S': 8, 'SE': 9, 'SSE': 10, 'SSW': 11, 'SW': 12, 'W': 13, 'WNW': 14, 'WSW': 15}
################
Location
{'AliceSprings': 0, 'Brisbane': 1, 'Cairns': 2, 'Canberra': 3, 'Cobar': 4, 'CoffsHarbour': 5, 'Darwin': 6, 'Hobart': 7, 'Melbourne': 8, 'MelbourneAirport': 9, 'Mildura': 10, 'Moree': 11, 'MountGambier': 12, 'NorfolkIsland': 13, 'Nuriootpa': 14, 'Perth': 15, 'PerthAirport': 16, 'Portland': 17, 'Sale': 18, 'Sydney': 19, 'SydneyAirport': 20, 'To

/tmp/wsuser/ipykernel_164/3716255542.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])


In [ ]:
df

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
5939    2009-01-01         4     17.9     35.2       0.0         12.0   
5940    2009-01-02         4     18.4     28.9       0.0         14.8   
5942    2009-01-04         4     19.4     37.6       0.0         10.8   
5943    2009-01-05         4     21.9     38.4       0.0         11.4   
5944    2009-01-06         4     24.2     41.0       0.0         11.2   
...            ...       ...      ...      ...       ...          ...   
139108  2017-06-20         6     19.3     33.4       0.0          6.0   
139109  2017-06-21         6     21.2     32.6       0.0          7.6   
139110  2017-06-22         6     20.7     32.8       0.0          5.6   
139111  2017-06-23         6     19.5     31.8       0.0          6.2   
139112  2017-06-24         6     20.2     31.7       0.0          5.6   

        Sunshine  WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity3pm  \
5939        12.3           11           48.0           1  ...         13.0   
5940        13.0            8           37.0          10  ...          8.0   
5942        10.6            5           46.0           5  ...         22.0   
5943        12.2           14           31.0          14  ...         22.0   
5944         8.4           14           35.0           7  ...         15.0   
...          ...          ...            ...         ...  ...          ...   
139108      11.0            1           35.0           9  ...         32.0   
139109       8.6            0           37.0           9  ...         28.0   
139110      11.0            0           33.0           0  ...         23.0   
139111      10.6            2           26.0           9  ...         58.0   
139112      10.7            1           30.0           1  ...         32.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
5939         1006.3       1004.4       2.0       5.0     26.6     33.4   
5940         1012.9       1012.1       1.0       1.0     20.3     27.0   
5942         1012.3       1009.2       1.0       6.0     28.7     34.9   
5943         1012.7       1009.1       1.0       5.0     29.1     35.6   
5944         1010.7       1007.4       1.0       6.0     33.6     37.6   
...             ...          ...       ...       ...      ...      ...   
139108       1013.9       1010.5       0.0       1.0     24.5     32.3   
139109       1014.6       1011.2       7.0       0.0     24.8     32.0   
139110       1015.3       1011.8       0.0       0.0     24.8     32.1   
139111       1014.9       1010.7       1.0       1.0     24.8     29.2   
139112       1013.9       1009.7       6.0       5.0     25.4     31.0   

        RainToday  RISK_MM  RainTomorrow  
5939            0      0.0             0  
5940            0      0.0             0  
5942            0      0.0             0  
5943            0      0.0             0  
5944            0      0.0             0  
...           ...      ...           ...  
139108          0      0.0             0  
139109          0      0.0             0  
139110          0      0.0             0  
139111          0      0.0             0  
139112          0      0.0             0  

[56420 rows x 24 columns]

In [ ]:
for col in df.columns:
  print(col, df[col].dtype)

Date object
Location int64
MinTemp float64
MaxTemp float64
Rainfall float64
Evaporation float64
Sunshine float64
WindGustDir int64
WindGustSpeed float64
WindDir9am int64
WindDir3pm int64
WindSpeed9am float64
WindSpeed3pm float64
Humidity9am float64
Humidity3pm float64
Pressure9am float64
Pressure3pm float64
Cloud9am float64
Cloud3pm float64
Temp9am float64
Temp3pm float64
RainToday int64
RISK_MM float64
RainTomorrow int64


In [ ]:
df['Date'] = pd.to_datetime(df['Date'], 
 format = '%Y-%m-%d', 
 errors = 'coerce')
df

/tmp/wsuser/ipykernel_164/2138458512.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'],


Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
5939   2009-01-01         4     17.9     35.2       0.0         12.0   
5940   2009-01-02         4     18.4     28.9       0.0         14.8   
5942   2009-01-04         4     19.4     37.6       0.0         10.8   
5943   2009-01-05         4     21.9     38.4       0.0         11.4   
5944   2009-01-06         4     24.2     41.0       0.0         11.2   
...           ...       ...      ...      ...       ...          ...   
139108 2017-06-20         6     19.3     33.4       0.0          6.0   
139109 2017-06-21         6     21.2     32.6       0.0          7.6   
139110 2017-06-22         6     20.7     32.8       0.0          5.6   
139111 2017-06-23         6     19.5     31.8       0.0          6.2   
139112 2017-06-24         6     20.2     31.7       0.0          5.6   

        Sunshine  WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity3pm  \
5939        12.3           11           48.0           1  ...         13.0   
5940        13.0            8           37.0          10  ...          8.0   
5942        10.6            5           46.0           5  ...         22.0   
5943        12.2           14           31.0          14  ...         22.0   
5944         8.4           14           35.0           7  ...         15.0   
...          ...          ...            ...         ...  ...          ...   
139108      11.0            1           35.0           9  ...         32.0   
139109       8.6            0           37.0           9  ...         28.0   
139110      11.0            0           33.0           0  ...         23.0   
139111      10.6            2           26.0           9  ...         58.0   
139112      10.7            1           30.0           1  ...         32.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
5939         1006.3       1004.4       2.0       5.0     26.6     33.4   
5940         1012.9       1012.1       1.0       1.0     20.3     27.0   
5942         1012.3       1009.2       1.0       6.0     28.7     34.9   
5943         1012.7       1009.1       1.0       5.0     29.1     35.6   
5944         1010.7       1007.4       1.0       6.0     33.6     37.6   
...             ...          ...       ...       ...      ...      ...   
139108       1013.9       1010.5       0.0       1.0     24.5     32.3   
139109       1014.6       1011.2       7.0       0.0     24.8     32.0   
139110       1015.3       1011.8       0.0       0.0     24.8     32.1   
139111       1014.9       1010.7       1.0       1.0     24.8     29.2   
139112       1013.9       1009.7       6.0       5.0     25.4     31.0   

        RainToday  RISK_MM  RainTomorrow  
5939            0      0.0             0  
5940            0      0.0             0  
5942            0      0.0             0  
5943            0      0.0             0  
5944            0      0.0             0  
...           ...      ...           ...  
139108          0      0.0             0  
139109          0      0.0             0  
139110          0      0.0             0  
139111          0      0.0             0  
139112          0      0.0             0  

[56420 rows x 24 columns]

In [ ]:
for col in df.columns:
  print(col, df[col].dtype)

Date datetime64[ns]
Location int64
MinTemp float64
MaxTemp float64
Rainfall float64
Evaporation float64
Sunshine float64
WindGustDir int64
WindGustSpeed float64
WindDir9am int64
WindDir3pm int64
WindSpeed9am float64
WindSpeed3pm float64
Humidity9am float64
Humidity3pm float64
Pressure9am float64
Pressure3pm float64
Cloud9am float64
Cloud3pm float64
Temp9am float64
Temp3pm float64
RainToday int64
RISK_MM float64
RainTomorrow int64


In [ ]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df

/tmp/wsuser/ipykernel_164/1056399479.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['Date'].dt.year
/tmp/wsuser/ipykernel_164/1056399479.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['Date'].dt.month
/tmp/wsuser/ipykernel_164/1056399479.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
5939   2009-01-01         4     17.9     35.2       0.0         12.0   
5940   2009-01-02         4     18.4     28.9       0.0         14.8   
5942   2009-01-04         4     19.4     37.6       0.0         10.8   
5943   2009-01-05         4     21.9     38.4       0.0         11.4   
5944   2009-01-06         4     24.2     41.0       0.0         11.2   
...           ...       ...      ...      ...       ...          ...   
139108 2017-06-20         6     19.3     33.4       0.0          6.0   
139109 2017-06-21         6     21.2     32.6       0.0          7.6   
139110 2017-06-22         6     20.7     32.8       0.0          5.6   
139111 2017-06-23         6     19.5     31.8       0.0          6.2   
139112 2017-06-24         6     20.2     31.7       0.0          5.6   

        Sunshine  WindGustDir  WindGustSpeed  WindDir9am  ...  Cloud9am  \
5939        12.3           11           48.0           1  ...       2.0   
5940        13.0            8           37.0          10  ...       1.0   
5942        10.6            5           46.0           5  ...       1.0   
5943        12.2           14           31.0          14  ...       1.0   
5944         8.4           14           35.0           7  ...       1.0   
...          ...          ...            ...         ...  ...       ...   
139108      11.0            1           35.0           9  ...       0.0   
139109       8.6            0           37.0           9  ...       7.0   
139110      11.0            0           33.0           0  ...       0.0   
139111      10.6            2           26.0           9  ...       1.0   
139112      10.7            1           30.0           1  ...       6.0   

        Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  RainTomorrow  year  \
5939         5.0     26.6     33.4          0      0.0             0  2009   
5940         1.0     20.3     27.0          0      0.0             0  2009   
5942         6.0     28.7     34.9          0      0.0             0  2009   
5943         5.0     29.1     35.6          0      0.0             0  2009   
5944         6.0     33.6     37.6          0      0.0             0  2009   
...          ...      ...      ...        ...      ...           ...   ...   
139108       1.0     24.5     32.3          0      0.0             0  2017   
139109       0.0     24.8     32.0          0      0.0             0  2017   
139110       0.0     24.8     32.1          0      0.0             0  2017   
139111       1.0     24.8     29.2          0      0.0             0  2017   
139112       5.0     25.4     31.0          0      0.0             0  2017   

        month  day  
5939        1    1  
5940        1    2  
5942        1    4  
5943        1    5  
5944        1    6  
...       ...  ...  
139108      6   20  
139109      6   21  
139110      6   22  
139111      6   23  
139112      6   24  

[56420 rows x 27 columns]

In [ ]:
del df['Date']

In [ ]:
df

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
5939           4     17.9     35.2       0.0         12.0      12.3   
5940           4     18.4     28.9       0.0         14.8      13.0   
5942           4     19.4     37.6       0.0         10.8      10.6   
5943           4     21.9     38.4       0.0         11.4      12.2   
5944           4     24.2     41.0       0.0         11.2       8.4   
...          ...      ...      ...       ...          ...       ...   
139108         6     19.3     33.4       0.0          6.0      11.0   
139109         6     21.2     32.6       0.0          7.6       8.6   
139110         6     20.7     32.8       0.0          5.6      11.0   
139111         6     19.5     31.8       0.0          6.2      10.6   
139112         6     20.2     31.7       0.0          5.6      10.7   

        WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Cloud9am  \
5939             11           48.0           1          12  ...       2.0   
5940              8           37.0          10          10  ...       1.0   
5942              5           46.0           5           6  ...       1.0   
5943             14           31.0          14          15  ...       1.0   
5944             14           35.0           7          14  ...       1.0   
...             ...            ...         ...         ...  ...       ...   
139108            1           35.0           9           4  ...       0.0   
139109            0           37.0           9           9  ...       7.0   
139110            0           33.0           0          13  ...       0.0   
139111            2           26.0           9           6  ...       1.0   
139112            1           30.0           1           6  ...       6.0   

        Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  RainTomorrow  year  \
5939         5.0     26.6     33.4          0      0.0             0  2009   
5940         1.0     20.3     27.0          0      0.0             0  2009   
5942         6.0     28.7     34.9          0      0.0             0  2009   
5943         5.0     29.1     35.6          0      0.0             0  2009   
5944         6.0     33.6     37.6          0      0.0             0  2009   
...          ...      ...      ...        ...      ...           ...   ...   
139108       1.0     24.5     32.3          0      0.0             0  2017   
139109       0.0     24.8     32.0          0      0.0             0  2017   
139110       0.0     24.8     32.1          0      0.0             0  2017   
139111       1.0     24.8     29.2          0      0.0             0  2017   
139112       5.0     25.4     31.0          0      0.0             0  2017   

        month  day  
5939        1    1  
5940        1    2  
5942        1    4  
5943        1    5  
5944        1    6  
...       ...  ...  
139108      6   20  
139109      6   21  
139110      6   22  
139111      6   23  
139112      6   24  

[56420 rows x 26 columns]

In [ ]:
for col in df.columns:
  print(col, df[col].dtype)

Location int64
MinTemp float64
MaxTemp float64
Rainfall float64
Evaporation float64
Sunshine float64
WindGustDir int64
WindGustSpeed float64
WindDir9am int64
WindDir3pm int64
WindSpeed9am float64
WindSpeed3pm float64
Humidity9am float64
Humidity3pm float64
Pressure9am float64
Pressure3pm float64
Cloud9am float64
Cloud3pm float64
Temp9am float64
Temp3pm float64
RainToday int64
RISK_MM float64
RainTomorrow int64
year int64
month int64
day int64


In [ ]:
X = df.drop('RainTomorrow', axis=1)
Y = df['RainTomorrow']

In [ ]:
X

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
5939           4     17.9     35.2       0.0         12.0      12.3   
5940           4     18.4     28.9       0.0         14.8      13.0   
5942           4     19.4     37.6       0.0         10.8      10.6   
5943           4     21.9     38.4       0.0         11.4      12.2   
5944           4     24.2     41.0       0.0         11.2       8.4   
...          ...      ...      ...       ...          ...       ...   
139108         6     19.3     33.4       0.0          6.0      11.0   
139109         6     21.2     32.6       0.0          7.6       8.6   
139110         6     20.7     32.8       0.0          5.6      11.0   
139111         6     19.5     31.8       0.0          6.2      10.6   
139112         6     20.2     31.7       0.0          5.6      10.7   

        WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Pressure3pm  \
5939             11           48.0           1          12  ...       1004.4   
5940              8           37.0          10          10  ...       1012.1   
5942              5           46.0           5           6  ...       1009.2   
5943             14           31.0          14          15  ...       1009.1   
5944             14           35.0           7          14  ...       1007.4   
...             ...            ...         ...         ...  ...          ...   
139108            1           35.0           9           4  ...       1010.5   
139109            0           37.0           9           9  ...       1011.2   
139110            0           33.0           0          13  ...       1011.8   
139111            2           26.0           9           6  ...       1010.7   
139112            1           30.0           1           6  ...       1009.7   

        Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  year  month  \
5939         2.0       5.0     26.6     33.4          0      0.0  2009      1   
5940         1.0       1.0     20.3     27.0          0      0.0  2009      1   
5942         1.0       6.0     28.7     34.9          0      0.0  2009      1   
5943         1.0       5.0     29.1     35.6          0      0.0  2009      1   
5944         1.0       6.0     33.6     37.6          0      0.0  2009      1   
...          ...       ...      ...      ...        ...      ...   ...    ...   
139108       0.0       1.0     24.5     32.3          0      0.0  2017      6   
139109       7.0       0.0     24.8     32.0          0      0.0  2017      6   
139110       0.0       0.0     24.8     32.1          0      0.0  2017      6   
139111       1.0       1.0     24.8     29.2          0      0.0  2017      6   
139112       6.0       5.0     25.4     31.0          0      0.0  2017      6   

        day  
5939      1  
5940      2  
5942      4  
5943      5  
5944      6  
...     ...  
139108   20  
139109   21  
139110   22  
139111   23  
139112   24  

[56420 rows x 25 columns]

In [ ]:
np.max(df['Temp3pm'].values), np.min(df['Temp3pm'].values)

(46.1, 3.7)

In [ ]:
np.max(df['MinTemp'].values), np.min(df['MinTemp'].values)

(31.4, -6.7)

In [ ]:
Y

5939      0
5940      0
5942      0
5943      0
5944      0
         ..
139108    0
139109    0
139110    0
139111    0
139112    0
Name: RainTomorrow, Length: 56420, dtype: int64

In [ ]:
Y.value_counts()

0    43993
1    12427
Name: RainTomorrow, dtype: int64

In [ ]:
X.shape, Y.shape

((56420, 25), (56420,))

#Normalization

In [ ]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-1.18184371,  0.69120848,  1.57529783, ..., -1.31421102,
        -1.57185009, -1.67651525],
       [-1.18184371,  0.76913098,  0.67150378, ..., -1.31421102,
        -1.57185009, -1.5626518 ],
       [-1.18184371,  0.92497598,  1.91960032, ..., -1.31421102,
        -1.57185009, -1.33492489],
       ...,
       [-0.90791487,  1.12757448,  1.23099533, ...,  1.94982075,
        -0.1231427 ,  0.71461729],
       [-0.90791487,  0.94056048,  1.08753596, ...,  1.94982075,
        -0.1231427 ,  0.82848075],
       [-0.90791487,  1.04965198,  1.07319002, ...,  1.94982075,
        -0.1231427 ,  0.9423442 ]])

In [ ]:
f = open("scaler.pkl", "wb")
pickle.dump(scaler, f)
f.close()

In [ ]:
np.random.seed(2)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(42315, 25)
(14105, 25)
(42315,)
(14105,)


#Model Training

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
def get_score(name, model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(model)
    print()

    score = metrics.accuracy_score(y_test,pred)
    cm = metrics.confusion_matrix(y_test,pred, labels = [0,1])
    print(cm)
    print()
    print("Training Accuracy : ",model.score(X_train, y_train))
    print()
    print("Testing Accuracy : ",model.score(X_test, y_test))
    print()

    joblib.dump(model, str(name)+str(model.score(X_test, y_test))+".joblib")
    print("################")
    return(model, model.score(X_test, y_test))
  
lr, result = get_score("lr", LogisticRegression(solver='liblinear',multi_class='ovr', 
                                   class_weight='balanced'), 
          x_train, x_test, y_train, y_test)

#svm, result = get_score("svm", SVC(gamma='auto', probability=True, class_weight='balanced'), 
#          x_train, x_test, y_train, y_test)

rf, result = get_score("rf", RandomForestClassifier(n_estimators=69, class_weight='balanced'), 
          x_train, x_test, y_train, y_test)

knn, result = get_score("knn", KNeighborsClassifier(n_neighbors = 2,), 
          x_train, x_test, y_train, y_test)

sgd, result = get_score("sgd", SGDClassifier(alpha=0.0001, average=False, class_weight='balanced',
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss="modified_huber",
              max_iter=50, n_iter_no_change=5, n_jobs=None, penalty='none',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False), x_train, x_test, y_train, y_test)


LogisticRegression(class_weight='balanced', multi_class='ovr',
                   solver='liblinear')

[[10940    82]
 [    1  3082]]

Training Accuracy :  0.9946591043365237

Testing Accuracy :  0.9941155618574974

################
RandomForestClassifier(class_weight='balanced', n_estimators=69)

[[11022     0]
 [    0  3083]]

Training Accuracy :  1.0

Testing Accuracy :  1.0

################
KNeighborsClassifier(n_neighbors=2)

[[10781   241]
 [ 1766  1317]]

Training Accuracy :  0.9148056244830438

Testing Accuracy :  0.8577100319035803

################
SGDClassifier(class_weight='balanced', loss='modified_huber', max_iter=50,
              penalty='none')

[[11021     1]
 [    0  3083]]

Training Accuracy :  1.0

Testing Accuracy :  0.9999291031549096

################


In [ ]:
os.getcwd(), os.listdir()

('/home/wsuser/work', ['rf1.0.joblib', 'scaler.pkl', '.virtual_documents'])

In [ ]:
cos_client.upload_file(Filename='scaler.pkl',Bucket=bucket,Key='scaler.pkl')

In [ ]:
cos_client.upload_file(Filename='rf1.0.joblib',Bucket=bucket,Key='rf1.1.joblib')

In [ ]:
dirs = dir(cos_client)
','.join(dirs)

'_PY_TO_OP_NAME,__class__,__delattr__,__dict__,__dir__,__doc__,__eq__,__format__,__ge__,__getattr__,__getattribute__,__gt__,__hash__,__init__,__init_subclass__,__le__,__lt__,__module__,__ne__,__new__,__reduce__,__reduce_ex__,__repr__,__setattr__,__sizeof__,__str__,__subclasshook__,__weakref__,_cache,_client_config,_convert_to_request_dict,_emit_api_params,_endpoint,_exceptions,_exceptions_factory,_get_waiter_config,_load_exceptions,_loader,_make_api_call,_make_request,_register_handlers,_request_signer,_response_parser,_serializer,_service_model,abort_multipart_upload,add_legal_hold,can_paginate,complete_multipart_upload,copy,copy_object,create_bucket,create_multipart_upload,delete_bucket,delete_bucket_analytics_configuration,delete_bucket_cors,delete_bucket_inventory_configuration,delete_bucket_lifecycle,delete_bucket_metrics_configuration,delete_bucket_policy,delete_bucket_replication,delete_bucket_tagging,delete_bucket_website,delete_legal_hold,delete_object,delete_object_tagging,de

In [ ]:
help(cos_client.upload_file)

Help on method upload_file in module ibm_boto3.s3.inject:

upload_file(Filename, Bucket, Key, ExtraArgs=None, Callback=None, Config=None) method of ibm_botocore.client.S3 instance
    Upload a file to an S3 object.
    
    Usage::
    
        import ibm_boto3
        s3 = ibm_boto3.resource('s3')
        s3.meta.client.upload_file('/tmp/hello.txt', 'mybucket', 'hello.txt')
    
    Similar behavior as S3Transfer's upload_file() method,
    except that parameters are capitalized. Detailed examples can be found at
    :ref:`S3Transfer's Usage <ref_ibm_s3transfer_usage>`.
    
    :type Filename: str
    :param Filename: The path to the file to upload.
    
    :type Bucket: str
    :param Bucket: The name of the bucket to upload to.
    
    :type Key: str
    :param Key: The name of the key to upload to.
    
    :type ExtraArgs: dict
    :param ExtraArgs: Extra arguments that may be passed to the
        client operation.
    
    :type Callback: function
    :param Callback: A metho

#Inference

In [ ]:
rf = joblib.load("rf1.0.joblib")

bucket = 'rainfall-donotdelete-pr-eoii6hshulobg1'
object_key = 'rainfall.csv'
body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df

df = df.dropna()
df

for i in df.columns:
  print(i, df[i].dtype)
  print(df[i].value_counts())
  print("################")

cols = ['RainToday', 'RainTomorrow', 'WindDir3pm', 'WindDir9am', 'WindGustDir', 'Location']

le = LabelEncoder()
for col in cols:
  print(col)
  df[col] = le.fit_transform(df[col])
  le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
  print(le_name_mapping)
  print("################")

df

for col in df.columns:
  print(col, df[col].dtype)

df['Date'] = pd.to_datetime(df['Date'], 
 format = '%Y-%m-%d', 
 errors = 'coerce')
df

for col in df.columns:
  print(col, df[col].dtype)

df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df

del df['Date']

df

for col in df.columns:
  print(col, df[col].dtype)

X = df.drop('RainTomorrow', axis=1)
Y = df['RainTomorrow']

Date object
2010-11-16    25
2009-03-09    25
2009-03-28    25
2009-03-26    25
2010-05-17    25
              ..
2008-03-26     1
2008-03-25     1
2008-03-24     1
2008-03-23     1
2008-01-02     1
Name: Date, Length: 3416, dtype: int64
################
Location object
Darwin              3062
Perth               3025
Brisbane            2953
MelbourneAirport    2929
PerthAirport        2913
SydneyAirport       2870
Watsonia            2730
Mildura             2594
MountGambier        2465
NorfolkIsland       2464
Cairns              2444
Townsville          2419
WaggaWagga          2416
AliceSprings        2223
Nuriootpa           2008
Hobart              1939
Moree               1913
Melbourne           1898
Portland            1863
Woomera             1734
Sydney              1690
Sale                1678
CoffsHarbour        1380
Williamtown         1198
Canberra            1078
Cobar                534
Name: Location, dtype: int64
################
MinTemp float64
 13.0    349
 9.6

Location int64
MinTemp float64
MaxTemp float64
Rainfall float64
Evaporation float64
Sunshine float64
WindGustDir int64
WindGustSpeed float64
WindDir9am int64
WindDir3pm int64
WindSpeed9am float64
WindSpeed3pm float64
Humidity9am float64
Humidity3pm float64
Pressure9am float64
Pressure3pm float64
Cloud9am float64
Cloud3pm float64
Temp9am float64
Temp3pm float64
RainToday int64
RISK_MM float64
RainTomorrow int64
year int64
month int64
day int64


In [ ]:
t = X.iloc[0].values
t

array([4.0000e+00, 1.7900e+01, 3.5200e+01, 0.0000e+00, 1.2000e+01,
       1.2300e+01, 1.1000e+01, 4.8000e+01, 1.0000e+00, 1.2000e+01,
       6.0000e+00, 2.0000e+01, 2.0000e+01, 1.3000e+01, 1.0063e+03,
       1.0044e+03, 2.0000e+00, 5.0000e+00, 2.6600e+01, 3.3400e+01,
       0.0000e+00, 0.0000e+00, 2.0090e+03, 1.0000e+00, 1.0000e+00])

In [ ]:
#RainTomorrow
#{'No': 0, 'Yes': 1}
Y.iloc[0]

0

In [ ]:
scaled_X = scaler.transform([t])
scaled_X

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.18184371,  0.69120848,  1.57529783, -0.30370205,  1.75769102,
         1.21453661,  0.73336198,  0.53412623, -1.31371416,  0.93928202,
        -1.16235517,  0.02505519, -2.4779243 , -1.81226109, -1.58330258,
        -1.51300183, -0.80142825,  0.25441126,  1.27818584,  1.56362087,
        -0.53244519, -0.26878286, -1.31421102, -1.57185009, -1.67651525]])

In [ ]:
type(rf)

In [ ]:
#lr_val = lr.predict_proba(scaled_X)
#svm_val = svm.predict_proba(scaled_X)
rf_val = rf.predict_proba(scaled_X)
#knn_val = knn.predict_proba(scaled_X)
#sgd_val = sgd.predict_proba(scaled_X)

In [ ]:
print(rf_val)

[[1. 0.]]


In [ ]:
#RainTomorrow
#{'No': 0, 'Yes': 1}

In [ ]:
#RainTomorrow
#{'No': 0, 'Yes': 1}
Y.iloc[0]

scaled_X = scaler.transform([t])
scaled_X

#lr_val = lr.predict_proba(scaled_X)
#svm_val = svm.predict_proba(scaled_X)
rf_val = rf.predict_proba(scaled_X)
#knn_val = knn.predict_proba(scaled_X)
#sgd_val = sgd.predict_proba(scaled_X)

In [ ]:
a = (lr_val+svm_val+rf_val+knn_val+sgd_val)/5

In [ ]:
a